name: Update CFR Conflicts Data

on:
  schedule:
    # Run every day at 6:00 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-conflicts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run CFR conflict scraper
      run: |
        python main.py
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add cfr_conflicts.json cfr_conflicts.csv
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update CFR conflicts data - $(date '+%Y-%m-%d %H:%M:%S UTC')"
          git push origin main
        fi
